### ISSUE TITLE
Improve performance of Liquid::Block#render_all, Liquid::Context#variable, and Liquid::Context#resolve

### ISSUE THREAD

**Issue by parkr** [Shopify/liquid#457] opened 2014-10-12 21:28 UTC
I was watching an excellent talk by `@tmm1` at Ruby Kaigi 2014. Inspired last night at like 3 am, I started using his `stackprof` utility to profile Jekyll and try to make it more efficient. I identified a bunch of small but sizable wins so far. Looks like some of the big culprits now slowing down Jekyll builds are calls to three pieces of Liquid: `Liquid::Block#render_all`, `Liquid::Context#variable`, and `Liquid::Context#resolve`.

Here's the stackprof output for running Jekyll against the current jekyllrb.com site source, arrows are mine:

```text
==================================
  Mode: cpu(1000)
  Samples: 1873 (0.43% miss rate)
  GC: 338 (18.05%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
       413  (22.1%)         413  (22.1%)     Jekyll::Tags::IncludeTag#includes_dir
       101   (5.4%)         101   (5.4%)     Kramdown::Utils::StringScanner#best_pos
        62   (3.3%)          62   (3.3%)     Kramdown::Parser::Kramdown#parse_first_list_line
        88   (4.7%)          52   (2.8%)     Jekyll::Utils#deep_merge_hashes
       349  (18.6%)          51   (2.7%)     Liquid::Context#variable                      <=====
        48   (2.6%)          48   (2.6%)     Jekyll::Utils#slugify
       175   (9.3%)          42   (2.2%)     Kramdown::Parser::Kramdown#parse_list
        85   (4.5%)          36   (1.9%)     Kramdown::Parser::Kramdown#parse_spans
        36   (1.9%)          35   (1.9%)     block in Jekyll::Utils#deep_merge_hashes
        33   (1.8%)          33   (1.8%)     Liquid::Context#[]=
        82   (4.4%)          33   (1.8%)     Kramdown::Parser::Kramdown#parse_block_html
        46   (2.5%)          30   (1.6%)     Jekyll::URL#sanitize_url
       379  (20.2%)          30   (1.6%)     Liquid::Context#resolve                       <=====
        30   (1.6%)          24   (1.3%)     Sass::CacheStores::Base#store
       121   (6.5%)          20   (1.1%)     Kramdown::Utils::StringScanner#current_line_number
        19   (1.0%)          19   (1.0%)     Jekyll::URL#initialize
        18   (1.0%)          18   (1.0%)     block in Logger::LogDevice#write
        18   (1.0%)          18   (1.0%)     Liquid::Context#has_interrupt?
        18   (1.0%)          18   (1.0%)     Pygments::Popen#alive?
        16   (0.9%)          16   (0.9%)     block in Jekyll::URL#sanitize_url
       102   (5.4%)          15   (0.8%)     Jekyll::Document#url_placeholders
      3692 (197.1%)          15   (0.8%)     Liquid::Block#render_all                      <=====
        14   (0.7%)          14   (0.7%)     block in Liquid::Context#find_variable
        13   (0.7%)          11   (0.6%)     Jekyll::Converters::Markdown#matches
        17   (0.9%)          11   (0.6%)     Jekyll::Convertible#read_yaml
        76   (4.1%)          10   (0.5%)     block in Kramdown::Converter::Html#inner
        10   (0.5%)          10   (0.5%)     Kramdown::Element#initialize
         9   (0.5%)           9   (0.5%)     Kramdown::Parser::Kramdown#parse_codespan
      3677 (196.3%)           9   (0.5%)     block in Liquid::Block#render_all             <=====
         8   (0.4%)           8   (0.4%)     FileUtils#fu_mkdir
```

Any way we can speed those guys up? Would likely be a huge win for you as well in terms of shopify.com render times. :tada:

**Comment by fw42** [comment] 2015-05-09 04:22
@parkr can you generate a new benchmark with the current version of Jekyll (and Liquid)?

**Comment by parkr** [comment] 2015-05-09 05:53
You bet! Running that site produces:

```text
==================================
  Mode: cpu(100)
  Samples: 6232 (6.47% miss rate)
  GC: 829 (13.30%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
       892  (14.3%)         892  (14.3%)     Jekyll::Tags::IncludeTag#validate_path
       539   (8.6%)         426   (6.8%)     Jekyll::Utils#deep_merge_hashes
       784  (12.6%)         329   (5.3%)     Kramdown::Parser::Kramdown#parse_spans
       214   (3.4%)         214   (3.4%)     Jekyll::Utils#slugify
       139   (2.2%)         138   (2.2%)     block in Logger::LogDevice#write
       291   (4.7%)         126   (2.0%)     Kramdown::Parser::Kramdown#parse_block_html
       113   (1.8%)         113   (1.8%)     Jekyll::Tags::IncludeTag#read_file
       113   (1.8%)         113   (1.8%)     block in Jekyll::Utils#deep_merge_hashes
       109   (1.7%)         109   (1.7%)     Jekyll::URL#initialize
        97   (1.6%)          97   (1.6%)     Pygments::Popen#alive?
        97   (1.6%)          97   (1.6%)     Kramdown::Element#initialize
        89   (1.4%)          89   (1.4%)     Liquid::Context#[]=
        87   (1.4%)          87   (1.4%)     block in Jekyll::URL#sanitize_url
       311   (5.0%)          84   (1.3%)     block in Pygments::Popen#mentos
     12233 (196.3%)          80   (1.3%)     Liquid::Block#render_all
        77   (1.2%)          72   (1.2%)     Kramdown::Parser::Kramdown#parse_codespan
        70   (1.1%)          70   (1.1%)     FileUtils#fu_mkdir
        70   (1.1%)          70   (1.1%)     Liquid::Context#has_interrupt?
       173   (2.8%)          69   (1.1%)     Kramdown::Parser::Kramdown#parse_list
        68   (1.1%)          68   (1.1%)     Kramdown::Utils::StringScanner#current_line_number
        61   (1.0%)          60   (1.0%)     Time.parse
        73   (1.2%)          59   (0.9%)     Kramdown::Parser::Html::Parser#parse_html_attributes
       518   (8.3%)          53   (0.9%)     block in Kramdown::Converter::Html#inner
       138   (2.2%)          51   (0.8%)     Jekyll::URL#sanitize_url
       279   (4.5%)          42   (0.7%)     Jekyll::Document#url_placeholders
        94   (1.5%)          40   (0.6%)     <class:Kramdown>
        37   (0.6%)          37   (0.6%)     #<Module:0x007fd891a5e350>.sanitized_path
      1319  (21.2%)          36   (0.6%)     Liquid::Context#evaluate
        31   (0.5%)          31   (0.5%)     Jekyll::Utils#add_permalink_suffix
        49   (0.8%)          27   (0.4%)     Liquid::Expression.parse
```

Still a good showing by Liquid.

**Comment by fw42** [comment] 2015-05-09 14:35
Could you post the exact command you used to generate this profile and how to reproduce it? This is on the gh-pages branch of the Jekyll repository?

**Comment by pushrax** [comment] 2015-05-09 14:38
btw, I have a PR at https://github.com/tmm1/stackprof/pull/41 to make `--limit` work with `--graphviz` for the stackprof command, so you can do stuff like `stackprof [file.dump] --graphviz --limit 500`.

**Comment by parkr** [comment] 2015-05-09 18:01
> Could you post the exact command you used to generate this profile and how to reproduce it? This is on the gh-pages branch of the Jekyll repository?

@fw42 Clone `jekyll/jekyll` and run `script/stackprof`.

**Comment by fw42** [comment] 2015-05-10 14:39
Ok I can reproduce now. I can see that most of what happens in Liquid::Context seems to be a bottle-neck for Jekyll, especially variable lookup. Not sure how to speed this up though :-/

**Comment by fw42** [comment] 2015-05-10 15:15
This is with Jekyll master (https://github.com/jekyll/jekyll/commit/221c0b62b61a) and Liquid master (724d625f47972c):

```
Configuration file: site/_config.yml
            Source: site
       Destination: /home/vagrant/src/jekyll/_site
 Incremental build: disabled
      Generating...
                    done in 3.579 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
==================================
  Mode: cpu(100)
  Samples: 812 (1.46% miss rate)
  GC: 67 (8.25%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
       113  (13.9%)          55   (6.8%)     Kramdown::Parser::Kramdown#parse_spans
        41   (5.0%)          39   (4.8%)     Liquid::Context#[]=
        26   (3.2%)          25   (3.1%)     block in Jekyll::Utils#deep_merge_hashes
        22   (2.7%)          22   (2.7%)     Liquid::Context#has_interrupt?
        21   (2.6%)          21   (2.6%)     Liquid::Lexer#tokenize
        21   (2.6%)          21   (2.6%)     Liquid::ResourceLimits#reached?
       167  (20.6%)          20   (2.5%)     Liquid::Context#evaluate
      1801 (221.8%)          19   (2.3%)     block in Liquid::BlockBody#render
        19   (2.3%)          19   (2.3%)     Liquid::Context#lookup_and_evaluate
        16   (2.0%)          16   (2.0%)     block in Liquid::Context#find_variable
      1816 (223.6%)          15   (1.8%)     Liquid::BlockBody#render
        14   (1.7%)          14   (1.7%)     Jekyll::Post#relative_path
        13   (1.6%)          13   (1.6%)     Kramdown::Element#initialize
        14   (1.7%)          13   (1.6%)     Jekyll::Tags::IncludeTag#read_file
       117  (14.4%)          13   (1.6%)     Liquid::Context#find_variable
        11   (1.4%)          11   (1.4%)     block (2 levels) in Pygments::Popen#mentos
        37   (4.6%)          10   (1.2%)     Kramdown::Parser::Kramdown#parse_block_html
       107  (13.2%)          10   (1.2%)     Liquid::Condition#interpret_condition
        10   (1.2%)          10   (1.2%)     Kramdown::Utils::StringScanner#current_line_number
        18   (2.2%)          10   (1.2%)     Liquid::Expression.parse
       127  (15.6%)          10   (1.2%)     Liquid::BlockBody#parse
      1762 (217.0%)           9   (1.1%)     Liquid::BlockBody#render_token
         9   (1.1%)           9   (1.1%)     Kramdown::Utils::Html#escape_html
        32   (3.9%)           9   (1.1%)     Kramdown::Parser::Kramdown#parse_list
        86  (10.6%)           9   (1.1%)     block (2 levels) in Kramdown::Parser::Kramdown#parse_blocks
         9   (1.1%)           8   (1.0%)     Liquid::Template#tokenize
        15   (1.8%)           8   (1.0%)     Kramdown::Parser::Base#add_text
        15   (1.8%)           8   (1.0%)     Liquid::Variable#taint_check
         8   (1.0%)           8   (1.0%)     Liquid::Condition#equal_variables
         8   (1.0%)           8   (1.0%)     Liquid::VariableLookup#initialize
```

**Comment by fw42** [comment] 2015-05-10 17:11
This is getting a bit off-topic re: Liquid, but something I found interesting when profiling Jekyll:

Number 3 on the list is `#deep_merge_hashes`. Why is this being called so much?

```
$ stackprof --method='Jekyll::Utils#deep_merge_hashes' tmp/stackprof-201505101653.dump

...

Jekyll::Utils#deep_merge_hashes (/home/vagrant/src/jekyll/lib/jekyll/utils.rb:20)
  samples:     1 self (0.1%)  /     24 total (3.0%)
  callers:
      22  (   91.7%)  Jekyll::Convertible#to_liquid
       1  (    4.2%)  Jekyll::Document#to_liquid
       1  (    4.2%)  Jekyll::Renderer#place_in_layouts
```

Lets look at why `Jekyll::Convertible#to_liquid` is being called so much:

```
$ stackprof --method='Jekyll::Convertible#to_liquid' tmp/stackprof-201505101653.dump

...

Jekyll::Convertible#to_liquid (/home/vagrant/src/jekyll/lib/jekyll/convertible.rb:124)
  samples:     0 self (0.0%)  /     71 total (8.8%)
  callers:
      70  (   98.6%)  Liquid::Context#find_variable
       1  (    1.4%)  Jekyll::Post#render
```

Hmm...

```
$ stackprof --method='Liquid::Context#find_variable' tmp/stackprof-201505101653.dump

...

    9    (1.1%) /     9   (1.1%)  |   164  |       if scope.nil?
    4    (0.5%)                   |   165  |         @environments.each do |e|
                                  |   166  |           variable = lookup_and_evaluate(e, key)
                                  |   167  |           unless variable.nil?
                                  |   168  |             scope = e
                                  |   169  |             break
                                  |   170  |           end
                                  |   171  |         end
                                  |   172  |       end
                                  |   173  |
    1    (0.1%) /     1   (0.1%)  |   174  |       scope     ||= @environments.last || @scopes.last
    5    (0.6%)                   |   175  |       variable  ||= lookup_and_evaluate(scope, key)
                                  |   176  |
   75    (9.3%)                   |   177  |       variable = variable.to_liquid
    8    (1.0%) /     8   (1.0%)  |   178  |       variable.context = self if variable.respond_to?(:context=)
```

That's [here](https://github.com/Shopify/liquid/blob/950f062041b9402dca5cf183bf60020ba56701d5/lib/liquid/context.rb#L177) (and it's calling back into Jekyll!).

Also note:

```
block in Jekyll::Convertible#to_liquid (/home/vagrant/src/jekyll/lib/jekyll/convertible.rb:125)
  samples:     1 self (0.1%)  /     41 total (5.1%)
  callers:
      41  (  100.0%)  Jekyll::Convertible#to_liquid
  callees (40 total):
      10  (   25.0%)  Jekyll::Post#path
       9  (   22.5%)  Jekyll::Post#excerpt_separator
       5  (   12.5%)  Jekyll::Post#next
       4  (   10.0%)  Jekyll::Post#id
       3  (    7.5%)  Jekyll::Post#excerpt
       3  (    7.5%)  Jekyll::Post#previous
       3  (    7.5%)  Jekyll::Post#url
       2  (    5.0%)  Jekyll::Post#title
       1  (    2.5%)  Jekyll::Post#dir
```

This might be a red herring, but I think it's sup-optimal that Jekyll uses `to_liquid` so much instead of `Liquid::Drop`. Jekyll "precomputes" a lot of data and puts it in a Hash that is returned by `to_liquid` in various places. Looking at the last thing I just posted, that means for example that the time we spend in `Jekyll::Post#excerpt_separator` is completely wasted if the template doesn't even use that (all this stuff is computed for every template, regardless of whether or not the template uses it). Using `Liquid::Drop` subclasses (where method calls only get evaluated if the template calls that method) might save some calls here and there. No idea if this is significant, but I imagine it could be.

@parkr, are there good reasons why Jekyll uses `to_liquid` so much and not `Liquid::Drop`?

**Comment by fw42** [comment] 2015-05-10 18:20
I guess someone else already had the same idea: https://github.com/jekyll/jekyll/issues/3224 -- FYI @envygeeks

**Comment by parkr** [comment] 2015-05-10 18:21
@fw42 We have the `data` attribute which has to get merged down into the proprietary things that Jekyll always provides. So if you have a `title` attribute in your YAML front matter, that has to be available as `page.title`. I suppose hook plugins (new as of like 3 days ago!) could use the data attribute if that could be folded into this. Other than that, we're good to go.

**Comment by parkr** [comment] 2015-05-10 18:22
So what I get from this is that Jekyll is slow because Liquid is calling Jekyll which is, in turn, slow. So if we speed up Jekyll or use Liquid properly (drops) then we could see a great speed increase?

**Comment by fw42** [comment] 2015-05-10 18:25
> So what I get from this is that Jekyll is slow because Liquid is calling Jekyll which is, in turn, slow. So if we speed up Jekyll or use Liquid properly (drops) then we could see a great speed increase?

Yeah that's a possibility, but I'm not sure, I can't promise if it would actually improve things a lot. I don't want to just point the finger at Jekyll since certain parts of Liquid can be improved as well, I'm sure. It's just something that jumped out to me. Might be worth a try.

**Comment by parkr** [comment] 2015-05-10 19:01
> Might be worth a try.

I'm #UpForWhatever. Thoughts on the extensibility concerns in my earlier comment?

**Comment by fw42** [comment] 2015-05-10 19:27
Not sure, I don't understand Jekyll well enough to say that yet.

**Comment by fw42** [comment] 2015-06-09 18:14
Closing this issue for now since it doesn't seem very useful to keep it open ("please make things faster" is not super actionable).

**Closed by fw42** 2015-06-09 18:14 UTC
