### ISSUE TITLE
Removing of right curly brace is not possible

### ISSUE THREAD

**Issue by adius** [Shopify/liquid#863] opened 2017-02-17 20:34 UTC
This works: `{{ value | remove: '{' }}`, this doesn't: `{{ value | remove: '}' }}`.

A workaround is:

```
{% assign r_brace = '}' %}
{{ value | remove: r_brace }}
```

**Comment by fw42** [comment] 2017-02-17 20:52
yep this sucks. duplicate of https://github.com/Shopify/liquid/issues/213.

**Closed by fw42** 2017-02-17 20:52 UTC
