### ISSUE TITLE
Can't compare Fixnum with String but can perform math operation on String?

### ISSUE THREAD

**Issue by dyspop** [Shopify/liquid#646] opened 2015-08-21 20:39 UTC
Is this by design or a bug?

```
Liquid::Template.parse("{% if 1 > '0' %}true{%endif%}").render
 => "Liquid error: comparison of Fixnum with String failed" 
Liquid::Template.parse("{% assign test = '1' %}{{test | minus: 1}}").render
 => "0"
```

**Comment by fw42** [comment] 2015-10-06 19:13
I would say the fact that you can do math is by design. The fact that you can't also do comparisons sounds like a bug to me. @dylanahsmith, agree?

**Comment by dylanahsmith** [comment] 2015-10-06 19:40
Normally we try to coerce values based on the operation.  However, comparisons have different semantics based on type, so should we do string or numeric comparisons when given mixed types? E.g. `{% if "10" < 2 %}true{% endif %}` will give a different answer depending on whether we do a string or numeric comparison.

**Comment by fw42** [comment] 2015-10-06 19:41
Good point. So maybe we should not try to be smart here and just leave it as it is...

**Comment by pushrax** [comment] 2015-10-21 06:08
Going to close this issue since I think we agree that this is ambiguous and potentially dangerous behaviour. If someone makes a good case otherwise we can reopen.

**Closed by pushrax** 2015-10-21 06:08 UTC
