### ISSUE TITLE
Can no longer have spaces between brackets when accessing object properties in an assign statement.

### ISSUE THREAD

**Issue by mbarak** [Shopify/liquid#1334] opened 2020-10-27 14:18 UTC
Liquid can no longer have spaces between brackets when accessing object properties in an assign statement.

This code used to work and now doesn't:
```liquid
{%- assign mbarak_font_setting_value = settings[ 'header_top_nav_font_stack' ] -%}
{{ mbarak_font_setting_value }}
```
Note the spaces between the square brackets on the `settings` object.

This code use to return the value held by the object at the key provided but now returns the whole object - in this case `settings_data.json`.

I'm not sure if this issue is in [liquid](https://github.com/Shopify/liquid) or [liquid-c](https://github.com/Shopify/liquid-c)

**Comment by mbarak** [comment] 2020-10-27 14:25
Internal Shopify issue: https://github.com/Shopify/shopify/issues/266885

**Comment by pushrax** [comment] 2020-10-27 15:58
This is due to a major change to support more of Liquid inside Liquid-C, it should be fixed very soon.

**Comment by mbarak** [comment] 2020-10-28 12:38
This issue is still happening.

**Comment by dylanahsmith** [comment] 2020-10-28 13:35
It looks like the problem is now specific to the lax parser.

The variable markup `settings[ 'header_top_nav_font_stack' ] ` only has `settings[` matched by Liquid::QuotedFragment.  So even though `Liquid::Expression.parse` can handle the spaces in the quoted fragment, Liquid::QuotedFragment won't accept them.

I don't think we can just change `Liquid::QuotedFragment`, because it is used more extensively and I don't think a regular expression can recursively pattern match on nested square brackets the way the strict parser does.  So I think we want to scope the fix to Liquid::Variable lax parsing.

To stay compatible with liquid-c, I think the right approach would be to try to strict parse, then fallback to the lax parser as is done in liquid-c.

**Closed** 2020-10-28 14:37 UTC
Labels: BreaksCompatibility, Bug Report, Parser, Whitespace
