### ISSUE TITLE
json_parse filter

### ISSUE THREAD

**Issue by reggi** [Shopify/liquid#432] opened 2014-08-27 17:13 UTC
I'd really love a `json_parse` filter. The below code does not work to convert a json file to a server-side liquid object. It is however, very possible to convert a json file to a javascript variable, but it's sadly not server-side, and bad for SEO to have content rendered by the client.  I was going to attempt to break down the string using liquid itself but It's pretty hard. I've created objects with liquid in the past but they're quite crude you can check that out here, [the tweet](https://twitter.com/thomasreggi/status/400718974582665216), [the gist example](https://gist.github.com/reggi/7455604).

This is so simple for you guys to implement into production and it's a no brainer. 

```
{% capture quotes %}
  {% include "json.quotes" %}
{% endcapture %}

{% assign quotes = quotes.quotes[0].author | json_parse %}
{{ quotes.quotes[0].author }}

<script>
var quotes = JSON.parse({{ quotes | json }});
document.write(quotes.quotes[0].author);
</script>
```

I just tried to use the new [theming internationalization feature](https://s3.amazonaws.com/shopify-perf/i18n-beta/ShopifyThemeInternationalizationDocumentation.pdf), [I couldn't get it to work](https://twitter.com/thomasreggi/status/504676037104795648). 

Ideally this type of thing could just be done with locales. But it would still be nice to have a `json_parse`.

**Comment by tyteen4a03** [comment] 2015-02-04 09:30
Since `settings.html` does not allow Javascript, without `json_parse` I am required to use CSV if I want an array of values. I really prefer JSON over CSV.

Please add `json_parse`.

**Comment by robinbortlik** [comment] 2015-02-09 17:32
I was able to achieve this functionality by creating parse_json filter and then assign this result to variable in the template. Then you can simple access data as it should be an object. 
Here is the commit I made to locomotive_cms liquid extension.
https://github.com/robinbortlik/liquid_extensions/commit/2b7a67281b55f25045ec4c44813ddd7535b00b3d

```ruby
{% for event in contents.events %}
   {% assign json = event.content | as_json %}
   {% for ticket in json.tickets %}
       {{ ticket.end_date }}
  {% endfor %}
{% endfor %}
```

**Comment by tyteen4a03** [comment] 2015-02-09 17:36
Great, hopefully Shopify will add it soon.

**Comment by rickydazla** [comment] 2015-10-09 03:26
I would like this. For Shopify, tons of useful Variant-related yet non-price affecting data could be stored and used to manipulate the front-end, then tie in with Line Item Properties... :sweet_potato:

**Comment by horsejockey** [comment] 2015-11-16 18:03
Any news on this?  I would love to store json data in shopify metafields and then be able to parse it as liquid server side.  I can think of lots of awesome applications.

**Comment by coltonbrugger** [comment] 2015-12-11 13:55
What @horsejockey said!

>  I would love to store json data in [insert liquid-served tools'] metafields and then be able to parse it as liquid server side.

**Comment by sandect** [comment] 2015-12-23 03:44
Very helpful, need it!

**Comment by Panksy** [comment] 2016-01-08 14:12
I would also really like this. At the moment I am building and parsing a custom string array with unusual chars as delimiters.. Json would be so much nicer!

**Comment by mrpunkin** [comment] 2016-06-29 17:28
Yes, please! This would be a great solution for all sorts of various problems.

**Comment by ozzyogkush** [comment] 2016-09-01 18:35
The problem is that people will always use your system in unintended ways. In my case, I'm a software engineer being forced to use Jekyll - and from my perspective there are many things missing. Being able to create an array or hash in liquid directly seems like a no-brainer, as well as the ability to parse between these types without requiring individual plugins. Just my 0.02.

**Comment by kainjow** [comment] 2016-09-01 19:18
Two things I think could be added:

1. `json_parse` as mentioned by everyone else, doesn't seem difficult based on @robinbortlik's example
2. Creating hashes and arrays in Liquid directly, by looking for a starting { or [ character. For example:

    {% assign names = ['Steve', 'Bill', 'Larry'] %}

Or:

    {% assign person = {'name': 'Steve', age: 60} %}

Hash keys could be expressions that result in a string or int, and hash values and array items could be expressions resulting in any value. The Liquid strict parser could handle this pretty easily.

**Comment by reggi** [comment] 2016-09-29 18:51
@kainjow ideally with `json_parse` the you'd get what your talking about and the following would work.

```liquid
{% assign array = '["Steve", "Bill", "Larry"]' | json_parse %}
{{ array[0] }} // Steve
{% assign object = '{"name": "Steve", "age": 60}' | json_parse %}
{{ object.name }} // Steve
```

@fw42 Any idea if we'll ever get a `json_parse` filter?

**Comment by kainjow** [comment] 2016-09-29 18:56
@reggi yes, json can do it, but you're limited to hard coded strings. What if you want to use a variable exposed to Liquid already? Built-in support for the syntax would be far more powerful.

**Comment by patrickleet** [comment] 2016-09-30 21:17
```
function liquidToJSON(liquidString) {
  return JSON.parse(liquidString.replace(/=>/g, ': ').replace(/(\s)nil(\s|,)/g, '"nil",').replace(/Liquid::ImageDrop/g, '"Liquid::ImageDrop"').replace(/\}(|\s+){/g, '},{'));
} 
function JSONtoLiquid(json) {
  return JSON.stringify(json).replace(/\"(|\s+):(|\s+)/g, '"=>').replace(/"nil",/g, 'nil').replace(/"Liquid::ImageDrop"/g, 'Liquid::ImageDrop').replace(/\},(|\s+){/g, '}{');
}
```

**Comment by evulse** [comment] 2016-10-02 11:31
For anyone else tired of waiting for this

https://github.com/culturekings/shopify-json-parser

**Comment by jnorth** [comment] 2016-12-08 00:56
I'm also coming at this from a Shopify theme developer perspective, but I think a way to build up liquid objects through something like `json_parse` would be great for mocking objects. For example, this could be used for mocking up Shopify objects for section on-boarding.

```
{% if onboarding %}
  Create a mock article object
  {% json article %}
    {
      "title": {{ 'onboarding.article-excerpt.title' | t | json }},
      "content": {{ 'onboarding.article-excerpt.content' | t | json }}
    }
  {% endjson %}
{% endif %}

<div class="article-excerpt">
  <h1 class="article-excerpt-title">{{ article.title }}</h1>
  <div class="article-excerpt-content">{{ article.content }}</div>
</div>
```

Here's a longer example: https://gist.github.com/jnorth/2202368d02e9425d54e9e0bb3ee66887

**Comment by evulse** [comment] 2017-02-28 05:38
Solution for this in Pull Request #867 we have been using the liquid side JSON parsing but we have hit slow downs on our site which everyone knows means lost sales so we are proposing the attached to bring json parsing into the standard filter functions.

**Comment by celsowhite** [comment] 2017-05-13 19:18
Would love this feature. I'm currently trying to set a metafield value as a JSON object. This would be helpful when I'm using js to create a metafield using the [API](https://help.shopify.com/api/reference/metafield#create) then easily access key/values of that object in Liquid.

I realize I can create a bunch of different metafields with different keys and values but this would help make my requests and code more concise.

**Comment by rafaelsorto** [comment] 2018-02-05 23:09
Hi guys, what an interesting read I just had. Any news on the json_parser ?

I have a customer who is importing a lot of data via Airtable API from different tables and storing the file via Asset API inside the theme, but then there is no way to translate that file into shopify variables.

I had to read the file via javascript using getJSON and then doing everything else in Javascript Land. It would be very nice to have a Liquid Option.

Regards,
Rafael

**Comment by stephengardner** [comment] 2018-07-18 09:54
Another half-year and no update here.  I certainly need this feature.  Any update?

**Comment by marcsyp** [comment] 2018-08-20 20:13
![image](https://user-images.githubusercontent.com/2940820/44364064-03c29900-a494-11e8-8eb7-7ef1ef440258.png)

:)

**Comment by evulse** [comment] 2018-09-18 10:39
New json_string metafield is out and all I have to say is

![image](https://cultofthepartyparrot.com/parrots/middleparrot.gif) ![image](https://cultofthepartyparrot.com/parrots/middleparrot.gif) ![image](https://cultofthepartyparrot.com/parrots/middleparrot.gif) ![image](https://cultofthepartyparrot.com/parrots/middleparrot.gif)

I did get a little nervous as the example and wording seemed like it could possibly just be a single level object

![image](https://user-images.githubusercontent.com/1631174/45682000-5e7a0e00-bb82-11e8-9f19-36bd061bf9f9.png)

But testing proves it is the real deal

![image](https://user-images.githubusercontent.com/1631174/45681847-ead80100-bb81-11e8-8106-3addfea564a9.png)

Just a copy of my really dodgy test snippet `json-loop.liquid`

```
{% assign new_indent = indent | plus:20 %}
{% for key_value in json %}
  {% if key_value[0] %}
    <li style='margin-left:{{new_indent}}px'>🍻{{ key_value[0] }} = {{ key_value[1] }}</li>

  {% endif %}
  {% assign new_indent = new_indent | plus:20 %}
  {% for inner_key_value in key_value[1] %}
  {% if inner_key_value[1] or inner_key_value[0]  %}
  <li style='margin-left:{{new_indent}}px'>🍻 I can loop through key/value - {{ inner_key_value[0] }} = {{ inner_key_value[1] }}</li>
	{% include 'json-loop' json: inner_key_value[1] indent: new_indent  %}  
	{% elsif inner_key_value and key_value[0] != 'string' %}
  <li style='margin-left:{{new_indent}}px'>🍻 I can loop through value - {{ inner_key_value }}</li>
	{% include 'json-loop' json: inner_key_value indent: new_indent  %}
  {% endif %}
  {% endfor %}
 {% assign new_indent = new_indent | minus:20 %}
{% endfor %}
{% assign new_indent = new_indent | minus:20 %}
```
Plus test product metafield API call

```
{
  "metafield": {
    "namespace": "test",
    "key": "json",
    "value": "{\"string\":\"hello\",\"int\":9,\"int_array\":[8,9,10],\"string_array\":[\"one\",\"two\",\"three\"],\"object\":{\"string\":\"hello\",\"int\":9,\"int_array\":[8,9,10],\"string_array\":[\"one\",\"two\",\"three\"],\"object\":{\"string\":\"hello\",\"int\":9,\"int_array\":[8,9,10],\"string_array\":[\"one\",\"two\",\"three\"]}},\"object_array\":[{\"string\":\"hello\"},{\"int\":9}]}",
    "value_type": "json_string"
  }
}
```

**Comment by evulse** [comment] 2018-09-18 11:04
In the further good news...

```
<ul>
  <li>Try to access product.metafields.test['json']['object']['string_array'][0]</li>
  {% if product.metafields.test['json']['object']['string_array'][0]  %}
     <li>🍻 {{product.metafields.test['json']['object']['string_array'][0]}}</li>
  {% else %}
     <li>😢 No direct access</li>
  {% endif %}
  
  <li>Try to access product.metafields.test['json']['object_array'][0]['string']</li>
  {% if product.metafields.test['json']['object_array'][0]['string']  %}
    <li>🍻 {{product.metafields.test['json']['object_array'][0]['string']}}</li>
  {% else %}
     <li>😢 No direct access</li>
  {% endif %}
</ul>
```
Outcome
```
Try to access product.metafields.test['json']['object']['string_array'][0]
🍻 one
Try to access product.metafields.test['json']['object_array'][0]['string']
🍻 hello
```

**Comment by Thibaut** [comment] 2018-09-18 14:05
Shopify has introduced a `json_string` metafield value type, which you can read about [here](https://help.shopify.com/en/themes/liquid/objects/metafield). This makes it easy to store arbitrary structured data within the Shopify platform and access it inside Liquid templates.

As a result, we will not add a JSON parse filter to Liquid. Our worry is that developers would end up storing JSON strings in various places that are not properly modeled as JSON (e.g. string metafields), or worse, inline in the Liquid code (Liquid is a markup language designed to be simple and approachable).

**Closed by Thibaut** 2018-09-18 14:05 UTC
Labels: Feature Request

**Comment by xyyolab** [comment] 2020-07-29 13:49
For those who do not want to use `json_string ` metafield value.

 - create /snippets/example.liquid
```
<div id='json-data'>[{"id":1, "name":"apple"}, {"id":2, "name": "peach"},{"id":3, "name": "orange"}]</div>
```

- in the .liquid file you want to use json data
```
{% render 'example' %}
<script>
  const Items = JSON.parse(document.getElementById('json-data').textContent)
 // Here is the json data
</script>
```
This approach should faster than metafields approach or fetch data from API.

**Comment by EinfachHans** [comment] 2021-07-31 20:11
This does not work for me. I have a metafield declared as `json_string`.
If i add this (`<script>console.log({{ product.metafields.custom.ingredients }});</script>`) to my code, it successfully logs:

`{base: "Test"}`

but if i try to use `console.log({{ product.metafields.custom.ingredients.base }});` or use `{{ product.metafields.custom.ingredients.base }}` it just shows/prints nothing 🤔

Any help would be appreciated!

**Comment by mrpunkin** [comment] 2021-07-31 20:35
@EinfachHans I think you might be looking for the `json` filter. Give this a try:

`<script>console.log({{ product.metafields.custom.ingredients | json }});</script>`

**Comment by EinfachHans** [comment] 2021-07-31 20:36
No i'm not, i want to access the values of my json via the key

**Comment by mrpunkin** [comment] 2021-07-31 20:43
@EinfachHans In that case simply use your JSON object to set a variable, then call the properties on that new object stored to the variable.

```
var obj = {{ product.metafields.custom.ingredients }};
console.log(obj.base);
```

**Comment by EinfachHans** [comment] 2021-07-31 20:44
That does not work. Also i want to use it in my Liquid Template at the end like:

```
{{ product.metafields.custom.ingredients.base }}
```

**Comment by mrpunkin** [comment] 2021-07-31 20:58
@EinfachHans 

If it doesn't work it's not a properly formatted JSON string. Your given example of what you are storing is indeed not a valid JSON string as the key `base` isn't quoted like it should be in JSON.

However, that being said, what you are trying to do seems to require the use of Shopify's json_string metafield type. See this thread regarding the announcement for examples: https://community.shopify.com/c/API-Announcements/New-json-string-value-type-for-Metafield-object/td-p/465561

**Comment by EinfachHans** [comment] 2021-07-31 21:01
I appreciate your help, but did you read what i write? My first sentence here was:

> I have a metafield declared as `json_string`

It definitely is one and it is definitely a valid JSON string, as otherwise i wouldn't be able to save it in the Shopify Admin Overview. The Log output i added was from `<script>console.log({{ product.metafields.custom.ingredients }});</script>` which logs it correctly as an object

**Comment by agentfitz** [comment] 2023-03-07 03:05
Here we are in 2023. I am new to Liquid, but I am baffled that we cannot readily convert JSON objects to Liquid objects, and vice-versa. Even in the ancient language I come from, ColdFusion, we can easily do this:

```
<cfset jsonString = '{ "firstName": "Frank", "lastName": "The-Tank" }'>
<cfset serverObj = deserializeJson(jsonString)>
<cfset jsonString = serializeJson(serverObj)>
```

This is useful in an infinite number of use cases.

============

In liquid...

```
{% assign jsonString =  '{ "firstName": "Frank", "lastName": "The-Tank" }' %}
{% assign serverObj = jsonString | json_parse %}
{% assign jsonString = serverObj | json %}
```

THIS WOULD BE INCREDIBLY USEFUL. SHOPIFY DEVELOPER NEED THIS.

**Comment by danieltroger** [comment] 2023-08-09 08:57
> THIS WOULD BE INCREDIBLY USEFUL. SHOPIFY DEVELOPER NEED THIS.

I 100% agree. I'm trying to use metafields rn just to get an object into liquid and it's a pain, especially because chatGPT isn't super good at helping. My biggest hurdle has been figuring out where a backend can be ran that writes to the metafields, the documentation is *super* unclear about who will host/run a backend (it seems like shopify doesn't host any backend at all and the official app starter CLI hosts it for oneself for development using ngrok but on prod one has to do ??????).

Maybe as a workaround you could post a step to step guides for dummies that never have heard about shopify on how to do the whole backend, api communication, graphql metafield shenanigans
