### ISSUE TITLE
Liquid syntax errors when upgrading Liquid 2.6.1 ⇒ 3.0 via Jekyll

### ISSUE THREAD

**Issue by fj** [Shopify/liquid#538] opened 2015-03-19 14:40 UTC
I have this simple snippet in Jekyll 2.5.3, using Liquid 2.6.1, which renders correctly:

```
{% assign current = page.url | downcase | split: '/' %}
{% assign page.nav_highlight = 'blog' %}
# ...
  <a href="{{'/blog.html' | prepend: site.baseurl}}"
    {% if page.nav_highlight == 'blog' || current[1] == 'blog.html' %} class="active" {% endif %}
    title="Blog">
    Blog
  </a>
```

If I upgrade to Jekyll 3.0.0.pre.beta2, which uses Liquid 3.0, I instead get:

```
  Liquid Exception:
    Liquid syntax error: Expected end_of_string but found pipe in "page.nav_highlight == 'blog' || current[1] == 'blog.html'" in _includes/header.html, included in _layouts/measure-lg.html
```

Additionally, if I remove

```
{% assign page.nav_highlight = 'blog' %}
```

so that `nav_highlight` is no longer defined on `page`, I get a different error (probably because `nav_highlight` is now null):

```
  Liquid Exception:
    Liquid syntax error: Expected dotdot but found comparison in "(page.nav_highlight == 'blog' || current[1] == 'blog.html')" in _includes/header.html, included in _layouts/measure-lg.html
```

Neither error occurs in 2.6.1.

**Comment by fw42** [comment] 2015-03-19 14:43
`||` is not valid Liquid syntax (and never has been), you need to use `or`... the parser (in lax mode) just ignores those parts I think. The new parser raises a warning.

**Comment by fw42** [comment] 2015-03-19 14:44
so I guess what I'm saying is:

That code of yours is broken in Jekyll 2 as well, you just don't see the error message.

**Comment by fw42** [comment] 2015-03-19 14:48
This illustrates what I'm talking about:
```
irb(main):003:0> Liquid::Template.parse("{% if false or true %} foo {% else %} bar {% endif %}").render
=> " foo "

irb(main):002:0> irb(main):002:0> Liquid::Template.parse("{% if false || true %} foo {% else %} bar {% endif %}").render
=> " bar "

irb(main):005:0> Liquid::Template.error_mode = :strict
=> :strict
irb(main):006:0> Liquid::Template.parse("{% if false || true %} foo {% else %} bar {% endif %}").render
Liquid::SyntaxError: Liquid syntax error: Expected end_of_string but found pipe in "false || true"
```

**Comment by fw42** [comment] 2015-03-19 14:48
So, closing since this is not a bug in Liquid but a bug in your template

**Closed by fw42** 2015-03-19 14:48 UTC

**Comment by fj** [comment] 2015-03-19 14:50
You're right -- Jekyll must just never have been passing these errors along (or been using lax mode).

I do get a different set of errors after replacing `||` with `or`, though. I'll investigate further.

**Comment by arthur-flam** [comment] 2015-04-19 17:48
:+1: Same issue for me when I upgraded to Jekyll 3.0.0.pre.beta. A previously uncaught bad filter syntax broke my build. All good now !
