### ISSUE TITLE
Ater updating liquid not all Array methods are working

### ISSUE THREAD

**Issue by kritik** [Shopify/liquid#477] opened 2014-10-28 17:50 UTC
For example rails extends enumerable with the method many?
http://api.rubyonrails.org/classes/Enumerable.html#method-i-many-3F

before at f15d24509d0f429f56284da527e6186708a27725 liquid had method many? on array but after update up to d9ae36ec406432adbd2828e31c79731ebafc357b it returns nil.

What should I do to allow this method? I did ArrayDrop for now to handle it as collection but I don't think it's reasonable because Array methods are quite safe. Moreover liquid has code
```ruby
class Array  # :nodoc:
  def to_liquid
    self
  end
end
```

**Comment by fw42** [comment] 2015-06-09 18:17
> I (..) cannot reproduce that stage when code used to work, even if I define specific version.

Closing since we can't reproduce the problem

**Closed by fw42** 2015-06-09 18:17 UTC
