### ISSUE TITLE
rvm/gems/ruby-2.2.0/gems/liquid-2.5.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"

### ISSUE THREAD

**Issue by tonyynot** [Shopify/liquid#517] opened 2015-02-01 17:45 UTC
Each time I run a Jekyll command, I receive the following error: 

..rvm/gems/ruby-2.2.0/gems/liquid-2.5.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"

Is there a way I can manually remove the duplicated line in htmltags.rb?

**Comment by fw42** [comment] 2015-02-01 17:48
Duplicate of https://github.com/Shopify/liquid/issues/502. This was already fixed in https://github.com/Shopify/liquid/pull/503 and https://github.com/Shopify/liquid/pull/504.

**Closed by fw42** 2015-02-01 17:48 UTC
