### ISSUE TITLE
Chained access to multidimensional hash using variables as keys

### ISSUE THREAD

**Issue by Mingan** [Shopify/liquid#625] opened 2015-07-17 09:37 UTC
We're in a process of upgrading our website to use Jekyll 3. Apart from the normal issues, we've encountered some strange problems and one of them seems to be with Liquid.

In the past, we used Jekyll 2.5.3 with Liquid **2.6.1**, after update we have Jekyll 3.0.0.pre.beta8 and Liquid **3.0.3**.

Construction like 

    site.data.menu[include.menu][include.locale]

with variables `include.menu` and `include.locale` used to be legal and worked as expected. (We used this in a for loop to generate menu.)

In the version it fails with:

    Liquid syntax error: Expected end_of_string but found open_square in "{{site.data.menu[include.menu][include.locale]}}"

We managed to sidestep the problem by extracting the first level into a variable and then accessing the second one like:

    {% assign menus = site.data.menu[include.menu] %}
    {% for item in menus[include.locale] %}
         ...
    {% endfor %}

I couldn't find any mention about this functionality at all let alone about changes but since it's possible to access the hash in two steps I think it should be possible to do it in a single step as well.

**Comment by fw42** [comment] 2015-07-17 11:14
Interesting. I confirmed the problem. This indeed works with the lax parser (the default of Jekyll 2) but not the strict parser (the default of Jekyll 3).

Not sure why. It looks correct to me. @trishume @pushrax?

**Comment by trishume** [comment] 2015-07-17 13:25
Yah this is a bug in the strict parser. It only tries to parse one set of square brackets after a variable name.

This specific case could trivially be fixed by changing the `if` on this line to a `while`:
https://github.com/Shopify/liquid/blob/master/lib%2Fliquid%2Fparser.rb#L78

That might actually be a correct expression of the intended grammar but we should probably think about what the grammar should be and when we want those square brackets to make sure we allow them in all the right places.

**Comment by fw42** [comment] 2015-07-17 13:28
We should backport this fix to the 3.0 branch so that Jekyll can pick it up...

@parkr FYI

**Closed** 2015-07-17 15:19 UTC
Labels: Bug Report, Parser

**Comment by fw42** [comment] 2015-07-17 15:22
Thanks for reporting this issue!

**Comment by Mingan** [comment] 2015-07-18 15:08
Thank you, for fixing it so amazingly fast! :heart:
