### ISSUE TITLE
Improve the Processing time for `for` loops

### ISSUE THREAD

**Issue by parkr** [Shopify/liquid#508] opened 2015-01-13 21:05 UTC
In Jekyll's usage of `for` loops in Liquid, these loops are historically the worst offenders of increased time-to-generation. `for` loops can sometimes add a tenth of a second per iteration to the processing time. Is there any benchmarking work done on `for` loops? I've been planning to dig deeper with `stackprof` to understand where the inefficiencies lie. Could just be the repetition of `context.stack`.

If anyone has any immediate idea of where the bottleneck is, please don't hesitate to add that info!.

**Comment by fw42** [comment] 2015-01-13 21:21
I don't think anyone is looking into that specifically at the moment... Maybe @jasonhl or @pushrax might be interested.

**Comment by jasonhl** [comment] 2015-01-14 15:37
@parkr: Can you give a specific example of an offending template where the overhead of the for loop is a significant contributor to the overall time? I'd be happy to look into it but I'd like to make sure I'm using a "real" usecase as opposed to some contrived thing.

**Comment by pushrax** [comment] 2015-01-15 15:45
:+1: to what Jason said. I'm not sure that for loops are intrinsically slow (I haven't seen this while benchmarking), but this is definitely related to what I'm working on and I can investigate this avenue.

**Comment by parkr** [comment] 2015-01-15 19:29
The jekyllrb.com site is a great example. We added a `for` loop and noticed 2 extra seconds of regen time.

```liquid
{% for post in site.posts %}
  {% do_a_thing %}
{% endfor %}
```

I removed the body of the `for` loop and it shaved half a second off. So just iterating over our 32 posts took 1.5 sec on my rMBP. :/

I'll come up with some code to test in isolation soon. But our "performance advice" in Jekyll is to limit use of `for` loops as much as possible.

**Comment by fw42** [comment] 2015-01-15 19:32
and how expensive is ```{% do_a_thing %}```?

**Comment by parkr** [comment] 2015-01-15 19:33
@fw42 About half-a-second's worth of time for 32 posts.

**Comment by fw42** [comment] 2015-01-15 19:33
from what you are saying, it sounds like this is the fault of whatever happens in your loop body, not of the actual loop itself (even if the body is empty, Liquid will still do the iteration).

**Comment by parkr** [comment] 2015-01-15 19:34
But if the loop body is empty, it should just be doing `site.posts.each { |post| }`?

**Comment by fw42** [comment] 2015-01-15 19:35
This is really hard to debug without a concrete reproducible example

**Comment by pushrax** [comment] 2015-01-16 21:24
Could it be that loading `site.posts` was really slow?

**Comment by parkr** [comment] 2015-01-16 22:42
What is the loading procedure? The array is inly 32 items, but they aren't tiny items.

**Comment by fw42** [comment] 2015-01-16 22:58
I think we make a copy of the whole thing (before the iteration even starts), so if you are passing huge amounts of data to that for loop, that might be it.

See Liquid::Utils.slice_collection

**Comment by parkr** [comment] 2015-01-16 23:14
The array itself is just an array of pointers. You do a deep clone of everything?!

**Comment by pushrax** [comment] 2015-01-17 00:27
No, it's just a shallow clone. I was more thinking if it caused an AR load, but obviously for Jekyll that doesn't make sense.

**Comment by fw42** [comment] 2015-05-11 17:05
> We added a for loop and noticed 2 extra seconds of regen time.

@parkr: How can I reproduce this issue? Do you have a link to the commit (to your site) that introduced this performance regression?

**Comment by parkr** [comment] 2015-05-11 19:39
> @parkr: How can I reproduce this issue? Do you have a link to the commit (to your site) that introduced this performance regression?

@fw42 I don't really remember, sadly. Sorry about that! If you open `site/news/index.html` and loop over `site.posts` again, you might find it again. For me, doing that didn't change things much on `jekyll/jekyll#master`, probably due to your amazing caching work!

```text
Running Jekyll...
Configuration file: /Users/parker/jekyll/jekyll/site/_config.yml
            Source: /Users/parker/jekyll/jekyll/site
       Destination: /Users/parker/jekyll/jekyll/site/_site
 Incremental build: disabled
      Generating...
                    done in 2.754 seconds.
 Auto-regeneration: enabled for '/Users/parker/jekyll/jekyll/site'
Configuration file: /Users/parker/jekyll/jekyll/site/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
Opening in browser...
      Regenerating: 1 file(s) changed at 2015-05-11 12:37:57 ...done in 2.35594 seconds.
      Regenerating: 1 file(s) changed at 2015-05-11 12:38:03 ...done in 2.362456 seconds.
      Regenerating: 1 file(s) changed at 2015-05-11 12:38:09 ...done in 2.662419 seconds.
      Regenerating: 1 file(s) changed at 2015-05-11 12:38:16 ...done in 2.389913 seconds.
      Regenerating: 1 file(s) changed at 2015-05-11 12:38:24 ...done in 2.430236 seconds.
      Regenerating: 1 file(s) changed at 2015-05-11 12:38:30 ...done in 2.362424 seconds.
```

**Comment by fw42** [comment] 2015-06-09 18:20
Closing this since I have no idea how to even reproduce the problem

**Closed by fw42** 2015-06-09 18:20 UTC

**Comment by parkr** [comment] 2015-06-09 18:24
Your liquid profiler will help. It'd be even cooler if it were per-tag.
