### ISSUE TITLE
Incorrect "variable was not properly terminated with regexp" error

### ISSUE THREAD

**Issue by andrew-3** [Shopify/liquid#1502] opened 2021-12-28 15:51 UTC
If I do:

`Liquid::Template.parse("{{ '{}' }}")`

I get `Liquid::SyntaxError: Liquid syntax error: Variable '{{ '{}' was not properly terminated with regexp: /\}\}/` which is not correct.

Tested on version 5.1.0.

**Comment by andershagbard** [comment] 2022-01-06 09:42
Duplicate/Related https://github.com/Shopify/liquid/issues/1491

**Comment by Oscilllator** [comment] 2022-11-06 20:48
I also get an error with the string:
	$$f = \frac{1}{2\pi\sqrt{LC}} => L = \frac{1}{{C(2\pi f)}^2}$$

Error:
github-pages [2](https://github.com/Oscilllator/quartz_blog/actions/runs/3405934969/jobs/5664268934#step:10:2)27 | Error:  Liquid syntax error (line [5](https://github.com/Oscilllator/quartz_blog/actions/runs/3405934969/jobs/5664268934#step:10:5)5): Variable '{{C(2\pi f)}' was not properly terminated with regexp: /\}\}/

**Comment by dylanahsmith** [comment] 2022-11-07 16:22
Yup, this is a duplicate of https://github.com/Shopify/liquid/issues/1491

**Closed by dylanahsmith** 2022-11-07 16:22 UTC

**Comment by TidbitSoftware** [comment] 2024-09-07 08:38
> I also get an error with the string: f = 1 2 π L C => L = 1 C ( 2 π f ) 2 `$$f = \frac{1}{2\pi\sqrt{LC}} => L = \frac{1}{{C(2\pi f)}^2}$$` 

@Oscilllator I know this is old, but on the off chance you or someone else can benefit from this, I was able to resolve a similar issue (feeding a query to https://latex.codecogs.com/gif.latex) by making sure there's a space between consecutive opening braces,

`{{C -> { {C`
