### ISSUE TITLE
Special character issue with link_to_add_tag/link_to_remove_tag

### ISSUE THREAD

**Issue by gina3five** [Shopify/liquid#615] opened 2015-07-07 20:27 UTC
I'm getting an odd issue with the URL output in the link_to_add_tag/link_to_remove_tag filters for creating my own filter area. The issue seems to be with tags with special characters. For example, take the example of a tag "chains & links". Sometimes in the URL output, this is handled as 'chains-links', but sometimes I also get 'chains-amp-links'.

Here's a short video (no audio) showing some of this odd behavior in action: http://screencast.com/t/Kei7mGggBrBb Notice the URLs of the links I hover over in the bottom of the browser window.

This is the code for the filters used in the video:
<h3>Tag Filters</h3>
<ul>
{% for tag in collection.all_tags %}
{% if current_tags contains tag %}
  <li><span style="color:red;">REMOVE: {{ tag | link_to_remove_tag: tag }}</span></li>
{% else %}
<li>ADD: {{ tag | link_to_add_tag: tag }}</li>
{% endif %}
{% endfor %}
</ul>

I also noticed that ampersands in tags stored in collection.all tags are output as '&', but ampersands in tags in current_tags are output as '& amp ;', which makes things awkward for comparison.

**Comment by fw42** [comment] 2015-07-07 21:10
I believe this is a (known) Shopify bug, not a Liquid bug.

@carolineschnapp? You have seen this before, right?

**Comment by gina3five** [comment] 2015-07-07 21:20
Sorry, is there a better place to post this issue?

**Comment by carolineschnapp** [comment] 2015-07-07 21:37
Right I have, this is a Shopify Liquid bug, not a bug with Liquid.

**Comment by iamkeir** [comment] 2015-08-05 10:06
I am experiencing this too:

Basically, if you are showing all tags available within a collection and you happen to use a combination that returns no results AND one of the tags has an apostrophe (or other special character), the URL string breaks and attempts to encode the apostrophe.

See here and click on black's, blue's and green's:
https://taggy.myshopify.com/collections/all/
https://taggy.myshopify.com/collections/all/blacks+blues+greens

The links now have '-39-' instead of the standard handle.

I have posted this to the Shopify forums too:
https://ecommerce.shopify.com/c/ecommerce-design/t/bug-with-tags-and-special-characters-276812

**Comment by fw42** [comment] 2015-10-06 19:17
Closing since this has nothing to do with the liquid Ruby gem

**Closed by fw42** 2015-10-06 19:17 UTC
Labels: Bug Report

**Comment by pinguluk** [comment] 2022-01-05 01:26
I can't believe this bug still dates back to today, I have this issue as well with the ampersand in tags.

**Comment by pinguluk** [comment] 2022-01-06 09:58
Ok, so I managed to create a hack/workaround for it, by not using the link_to_add_tag and link_to_remove_tag filters and I've built the permalinks for the tags myself
https://gist.github.com/pinguluk/7d370e60ad765b6224aab478bc552e20
